### ISSUE TITLE
[API V2] Adicionar LICENSE ao projeto

### ISSUE THREAD

**Issue by larismourullo** [devtranslate/api#7]

**Comment by GuilhermeTerriaga** [comment]
Oi, eu tava procurando aqui por projetos com issues abertas do Hacktoberfest e cheguei aqui! Vocês estão procurando por ajuda? Se sim, qual Licença seria a mais adequada para o projeto?

**Comment by larismourullo** [comment]
Oi, tudo bem? Estamos precisando de ajuda sim, desculpa não ter adicionado uma descrição, esta um pouco corrido aqui, mas em resumo o projeto é open source precisamos adicionar uma Licença MIT dentro da branch v2 onde esta localizada a nova API que estamos implementando.
